is_gunlugu/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'is_gunlugu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^isler/', include("isler.urls", namespace="isler")),
)

isler/urls.py
from django.conf.urls import patterns, url

from isler import views

urlpatterns = patterns('',
                       url(r'^bugun/$', views.bugun, name='bugun'),
                       url(r'^not_kaydi/$', views.not_kaydi, name='not_kaydi'),
                       url(r'^problem_kaydi/$', views.problem_kaydi, name='problem_kaydi'),
                       url(r'^gorev_kaydi/$', views.gorev_kaydi, name='gorev_kaydi'),
                       url(r'^hatirlatma_kaydi/$', views.hatirlatma_kaydi, name='hatirlatma_kaydi'),
                       )
                     

isler/models.py
from django.db import models


class Is(models.Model):
	aciklama = models.TextField()
	gun = models.DateField(auto_now_add=True)
	olusturulma = models.DateTimeField(auto_now_add=True)
	guncellenme = models.DateTimeField(auto_now=True)
	class Meta:
		abstract = True


class Not(Is):
	tip = "not"


class Problem(Is):
	baslik = models.CharField(max_length=500)
	cozuldu = models.BooleanField(default=False)
	cozumu = models.TextField(blank=True, null=True)
	tip = "problem"


class Gorev(Is):
	baslik = models.CharField(max_length=500)
	yapildi = models.BooleanField(default=False)
	notlar = models.TextField(blank=True, null=True)
	tip = "gorev"


class Hatirlatma(Is):
	tarih = models.DateTimeField(blank=True, null=True)
	aktif = models.BooleanField(default=True)
	tip = "hatirlatma"

isler/forms.py
from django.forms import ModelForm
from django.forms import DateField

from isler.models import Not, Problem, Gorev, Hatirlatma


class NotForm(ModelForm):
	class Meta:
		model = Not


class ProblemForm(ModelForm):
	class Meta:
		model = Problem


class GorevForm(ModelForm):
	class Meta:
		model = Gorev

class HatirlatmaForm(ModelForm):
	#tarih = 
	class Meta:
		model = Hatirlatma

isler/views/ana.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datetime import datetime

from isler.models import Not, Problem, Gorev, Hatirlatma, Is


def bugun(request):
	bugunun_notlari = Not.objects.filter(gun=datetime.now())
	bugunun_problemleri = Problem.objects.filter(gun=datetime.now())
	bugunun_gorevleri = Gorev.objects.filter(gun=datetime.now())
	bugunun_hatirlatmalari = Hatirlatma.objects.filter(gun=datetime.now())
	return render(request, "isler/bugun.html", locals())

isler/views/gorev.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datetime import datetime

from isler.models import Gorev
from isler.forms import GorevForm


def gorev_kaydi(request):	
	if request.method == "POST":
		form  = GorevForm(request.POST)
		if form.is_valid():
			form.save()	
			return HttpResponseRedirect(reverse("isler:bugun"))
		else:
			return render(request, "isler/gorev_formu.html", locals())
	else:
		form  = GorevForm()
		return render(request, "isler/gorev_formu.html", locals())

isler/views/hatirlatma.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datetime import datetime

from isler.models import Hatirlatma
from isler.forms import HatirlatmaForm

def hatirlatma_kaydi(request):	
	if request.method == "POST":
		form  = HatirlatmaForm(request.POST)
		if form.is_valid():
			form.save()	
			return HttpResponseRedirect(reverse("isler:bugun"))
		else:
			return render(request, "isler/hatirlatma_formu.html", locals())
	else:
		form  = HatirlatmaForm()
		return render(request, "isler/hatirlatma_formu.html", locals())

isler/views/notlar.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datetime import datetime

from isler.models import Not
from isler.forms import NotForm


def not_kaydi(request):	
	if request.method == "POST":
		form  = NotForm(request.POST)
		if form.is_valid():
			form.save()	
			return HttpResponseRedirect(reverse("isler:bugun"))
		else:
			return render(request, "isler/not_formu.html", locals())
	else:
		form  = NotForm()
		return render(request, "isler/not_formu.html", locals())

isler/views/problem.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from datetime import datetime

from isler.models import Problem
from isler.forms import ProblemForm

def problem_kaydi(request):	
	if request.method == "POST":
		form  = ProblemForm(request.POST)
		if form.is_valid():
			form.save()	
			return HttpResponseRedirect(reverse("isler:bugun"))
		else:
			return render(request, "isler/problem_formu.html", locals())
	else:
		form  = ProblemForm()
		return render(request, "isler/problem_formu.html", locals())

isler/templates/isler/bugun.html
{% extends 'ana.html' %}

{% block icerik %}

	<div class="row">
		<div class="col-xs-9">
			{% if bugunun_notlari %}
				<div class="box" >
					<h3>Notlar:</h3>
					<div class="col-xs-12">					
						{% for kayit in bugunun_notlari %}
							<div style="margin:10px">
								<span class="label label-success pull-right">{{kayit.olusturulma}}</span>
								<div class="clearfix"></div>
								<div class="box"  style="background:#ffa; padding:10px">
								 {{kayit.aciklama}} 
								</div>
							</div>
						{% endfor %}					
					</div>
					<div class="clearfix"></div>
				</div>
			{%endif%}

			{% if bugunun_problemleri %}
				<div class="box" >
					<h3>Problemler:</h3>
					<div class="col-xs-12">
						{% for kayit in bugunun_problemleri %}
							<div style="margin:10px">
								<span class="label label-success pull-right">{{kayit.olusturulma}}</span>
								<div class="clearfix"></div>
								<div class="panel panel-danger">

									<div class="panel-heading">{{kayit.baslik}}</div>
							  		<div class="panel-body">
							    		{{kayit.aciklama}}
							  		</div>							  
								</div>
							</div>
						{% endfor %}						
					</div>
					<div class="clearfix"></div>
				</div>
			{% endif %}

			{% if bugunun_gorevleri %}
				<div class="box" >
					<h3>Yapılacaklar:</h3>
					<div class="col-xs-12">
						{% for kayit in bugunun_gorevleri %}
							<div style="margin:10px">
								<span class="label label-success pull-right">{{kayit.olusturulma}}</span>
								<div class="clearfix"></div>
								<div class="panel panel-info">

									<div class="panel-heading">{{kayit.baslik}}</div>
							  		<div class="panel-body">
							    		{{kayit.aciklama}}
							  		</div>							  
								</div>
							</div>
						{% endfor %}						
					</div>
					<div class="clearfix"></div>
				</div>
			{% endif %}


			{% if bugunun_hatirlatmalari %}
				<div class="box" >
					<h3>Hatırlatmalar:</h3>
					<div class="col-xs-12">
						{% for kayit in bugunun_hatirlatmalari %}
							<div style="margin:10px">
								<span class="label label-success pull-right">{{kayit.olusturulma}}</span>
								<div class="clearfix"></div>
								<div class="box"  style="background:#B3EAEB; padding:10px">

							    	{{kayit.aciklama}}
							  								  
								</div>
							</div>
						{% endfor %}						
					</div>
					<div class="clearfix"></div>
				</div>
			{% endif %}

		</div>
	</div>

{%endblock%}

isler/templates/isler/gorev_formu.html
{% extends 'genel_form.html' %}
{%block action_url %}
	{% url 'isler:gorev_kaydi' %}
{%endblock%}
{%block alanlar %}
	<tr>
		<td>{{form.baslik.label}}</td>
		<td>{{form.baslik}}</td>
	</tr>
	<tr>
		<td>{{form.aciklama.label}}</td>
		<td>{{form.aciklama}}</td>
	</tr>
	<tr>
		<td>{{form.yapildi.label}}</td>
		<td>{{form.yapildi}}</td>
	</tr>
	<tr>
		<td>{{form.notlar.label}}</td>
		<td>{{form.notlar}}</td>
	</tr>

	
{%endblock%}

isler/templates/isler/hatirlatma_formu.html
{% extends 'genel_form.html' %}
{%block action_url %}
	{% url 'isler:hatirlatma_kaydi' %}
{%endblock%}
{%block alanlar %}
	<tr>
		<td>{{form.aciklama.label}}</td>
		<td>{{form.aciklama}}</td>
	</tr>
	<tr>
		<td>{{form.tarih.label}}</td>
		<td>{{form.tarih}}</td>
	</tr>
	<tr>
		<td>{{form.aktif.label}}</td>
		<td>{{form.aktif}}</td>
	</tr>

	
{%endblock%}

isler/templates/isler/not_formu.html
{% extends 'genel_form.html' %}
{%block action_url %}
	{% url 'isler:not_kaydi' %}
{%endblock%}
{%block alanlar %}
	{% for alan in form %}
		<tr>
			<td>{{alan.label}}</td>
			<td>{{alan}}</td>
		</tr>
	{%endfor%}
{%endblock%}

isler/templates/isler/problem_formu.html
{% extends 'genel_form.html' %}
{%block action_url %}
	{% url 'isler:problem_kaydi' %}
{%endblock%}
{%block alanlar %}
	<tr>
		<td>{{form.baslik.label}}</td>
		<td>{{form.baslik}}</td>
	</tr>
	<tr>
		<td>{{form.aciklama.label}}</td>
		<td>{{form.aciklama}}</td>
	</tr>
	<tr>
		<td>{{form.cozuldu.label}}</td>
		<td>{{form.cozuldu}}</td>
	</tr>
	<tr>
		<td>{{form.cozumu.label}}</td>
		<td>{{form.cozumu}}</td>
	</tr>

	
{%endblock%}

templates/ana.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>İş Günlüğü</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/source_sans.css' %}">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

{%block header %}{%endblock%}
</head>
<body>
	<div style="margin:50px;">
		<a class="btn btn-warning" href="{% url 'isler:bugun'%}" >Bugün</a>
		<a class="btn btn-success" href="{% url 'isler:not_kaydi'%}" >Yeni Not</a>
		<a class="btn btn-danger" href="{% url 'isler:problem_kaydi'%}" >Yeni Problem</a>
		<a class="btn btn-info" href="{% url 'isler:gorev_kaydi'%}" >Yeni Görev</a>
		<a class="btn btn-info" href="{% url 'isler:hatirlatma_kaydi'%}" >Yeni Hatırlatma</a>
	</div>
	<div style="margin-left:50px;">
		{% block icerik %}{% endblock %}
	</div>
</body>
</html>

templates/genel_form.html
{%extends 'ana.html' %}
{% block icerik %}

{{form.errors}}

<form method="POST" action="{%block action_url %}{%endblock%}">

	{%csrf_token%}
	<table>
		{% block alanlar %}{%endblock%}
		<tr>
			<td></td>
			<td><input type="submit" value="Gönder"></td>
		</tr>
	</table>
</form>
{%endblock%}